//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sachem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoursSuivi
    {
        public int id_CoursReussi { get; set; }
        public Nullable<int> id_Sess { get; set; }
        public int id_Pers { get; set; }
        public Nullable<int> id_College { get; set; }
        public Nullable<int> id_Statut { get; set; }
        public Nullable<int> id_Cours { get; set; }
        public Nullable<int> resultat { get; set; }
        public string autre_Cours { get; set; }
        public string autre_College { get; set; }
    
        public virtual Cours Cours { get; set; }
        public virtual p_College p_College { get; set; }
        public virtual p_StatutCours p_StatutCours { get; set; }
        public virtual Personne Personne { get; set; }
        public virtual Session Session { get; set; }
    }
}
