//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sachem.Models
{
    public partial class CoursInteret
    {
        public int id_CoursInteret { get; set; }
        public int id_Inscription { get; set; }
        public int id_Cours { get; set; }
        public int Priorite { get; set; }
    
        public virtual Cours Cours { get; set; }
        public virtual Inscription Inscription { get; set; }
        public virtual Inscription Inscription1 { get; set; }
    }
}
