//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sachem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disponibilite
    {
        public int id_Dispo { get; set; }
        public int id_Inscription { get; set; }
        public int id_Jour { get; set; }
        public System.TimeSpan HeureDebut { get; set; }
        public System.TimeSpan HeureFin { get; set; }
        public int minutes { get; set; }
    
        public virtual Inscription Inscription { get; set; }
        public virtual p_Jour p_Jour { get; set; }
    }
}
