//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sachem.Models
{  
    public partial class EtuProgEtude
    {
        public int id_EtuProgEtude { get; set; }
        public int id_ProgEtu { get; set; }
        public int id_Etu { get; set; }
        public int id_Sess { get; set; }
    
        public virtual Personne Personne { get; set; }
        public virtual ProgrammeEtude ProgrammeEtude { get; set; }
        public virtual Session Session { get; set; }
    }
}
