//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sachem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupeEtudiant
    {
        public int id_GroupeEtudiant { get; set; }
        public int id_Groupe { get; set; }
        public int id_Etudiant { get; set; }
    
        public virtual Groupe Groupe { get; set; }
        public virtual Personne Personne { get; set; }
    }
}
