//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sachem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Groupe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Groupe()
        {
            this.GroupeEtudiant = new HashSet<GroupeEtudiant>();
        }
    
        public int id_Groupe { get; set; }
        public int id_Cours { get; set; }
        public int id_Sess { get; set; }
        public Nullable<int> id_Enseignant { get; set; }
        public int NoGroupe { get; set; }
    
        public virtual Cours Cours { get; set; }
        public virtual Personne Personne { get; set; }
        public virtual Session Session { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupeEtudiant> GroupeEtudiant { get; set; }
    }
}
