//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sachem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inscription
    {
        public int id_Inscription { get; set; }
        public int id_Sess { get; set; }
        public int id_Pers { get; set; }
        public int id_Statut { get; set; }
        public int id_TypeInscription { get; set; }
        public Nullable<bool> TransmettreInfoTuteur { get; set; }
        public string NoteSup { get; set; }
        public Nullable<bool> ContratEngagement { get; set; }
        public Nullable<bool> BonEchange { get; set; }
    }
}
