//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sachem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jumelage
    {
        public int id_Jumelage { get; set; }
        public int id_InscEleve { get; set; }
        public int id_InscrTuteur { get; set; }
        public int id_Sess { get; set; }
        public int id_Enseignant { get; set; }
        public int id_Jour { get; set; }
        public System.DateTime DateDebut { get; set; }
        public Nullable<System.DateTime> DateFin { get; set; }
        public int minutes { get; set; }
    
        public virtual Inscription Inscription { get; set; }
        public virtual Inscription Inscription1 { get; set; }
        public virtual p_Jour p_Jour { get; set; }
        public virtual Personne Personne { get; set; }
        public virtual Session Session { get; set; }
    }
}
