//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sachem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SACHEMEntities : DbContext
    {
        public SACHEMEntities()
            : base("name=SACHEMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Courriel> Courriel { get; set; }
        public virtual DbSet<Cours> Cours { get; set; }
        public virtual DbSet<EtuProgEtude> EtuProgEtude { get; set; }
        public virtual DbSet<Groupe> Groupe { get; set; }
        public virtual DbSet<GroupeEtudiant> GroupeEtudiant { get; set; }
        public virtual DbSet<p_Contact> p_Contact { get; set; }
        public virtual DbSet<p_HoraireInscription> p_HoraireInscription { get; set; }
        public virtual DbSet<p_Saison> p_Saison { get; set; }
        public virtual DbSet<p_Sexe> p_Sexe { get; set; }
        public virtual DbSet<p_TypeCourriel> p_TypeCourriel { get; set; }
        public virtual DbSet<p_TypeUsag> p_TypeUsag { get; set; }
        public virtual DbSet<Personne> Personne { get; set; }
        public virtual DbSet<ProgrammeEtude> ProgrammeEtude { get; set; }
        public virtual DbSet<Session> Session { get; set; }
    }
}
