//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sachem.Models
{
    
    public partial class p_Contact
    {
        public int id_Contact { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string Courriel { get; set; }
        public string Telephone { get; set; }
        public int? Poste { get; set; }
        public string Facebook { get; set; }
        public string SiteWeb { get; set; }
        public string Local { get; set; }
    }
}
