//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sachem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class p_TypeFormulaire
    {
        public int id_TypeFormulaire { get; set; }
        public Nullable<int> id_TypeInscription { get; set; }
        public string TypeFormulaire { get; set; }
    
        public virtual Formulaire Formulaire { get; set; }
        public virtual p_TypeInscription p_TypeInscription { get; set; }
    }
}
