//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sachem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suivi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Suivi()
        {
            this.ReponseQuestion = new HashSet<ReponseQuestion>();
        }
    
        public int id_Suivi { get; set; }
        public int id_Jumelage { get; set; }
        public int? id_Correcteur { get; set; }
        public int NoSemaine { get; set; }
        public bool Transmis { get; set; }
        public string Correction { get; set; }
        public DateTime? DateCorrection { get; set; }
        public bool? TransmisCorrige { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReponseQuestion> ReponseQuestion { get; set; }
    }
}
